### ISSUE TITLE
When source code releasing?

### ISSUE THREAD

**Issue by Xbbei** [zhaofang0627/AnchorUDF#1]
Hi,
 Thanks for great job to reconstruct garment 3d model from RGB image, I want to know when is source code released?

Thanks very much!
Baobei Xu

**Comment by zhaofang0627** [comment]
Hi Baobei,

Thank you for your interest! We plan to release the code at the end of this month.

Best,
Fang Zhao

**Comment by Xbbei** [comment]
> Hi Baobei,
> 
> Thank you for your interest! We plan to release the code at the end of this month.
> 
> Best, Fang Zhao

Hi, Zhao Fang,

Thanks for your public resources, but I can't find your pretrained model, could you provide it ?

Thanks very much!
Baobei Xu

**Comment by zhang-0515** [comment]
Hi，Zhao Fang,
I can't find your pretrained model, could you provide it? Thanks very much.

**Comment by zhaofang0627** [comment]
Hi,

The trained model and preprocessed data have been updated.


Best, 
Fang Zhao
