### ISSUE TITLE
Target Sampling Distribution

### ISSUE THREAD

**Issue by kampelmuehler** [zhaofang0627/AnchorUDF#10]
In the supplemental of the paper you state
```
To generate training point sets, we randomly sample
points on the ground-truth surface and displace them with
Gaussian distribution N (0, σ) along x, y and z axis, where
1% of points are sampled from σ = 0.08, 49% of points
from σ = 0.02 and 50% of points from σ = 0.003 as sug-
gested by [13]
```
, yet the data preparation you provide only takes a single sigma. Is this intentional?

**EDIT:** (answering my own question)
The selection of samples according to the three different values of σ is taken care of during data loading - see https://github.com/zhaofang0627/AnchorUDF/blob/7df547fc89ac4c246300d6aba8a708e4b196d41b/lib/data/TrainDatasetDF3D.py#L228

I would suggest changing the README from

`python -m apps.gen_targets --dataroot {path_of_dataset} --sigma {0.003, 0.02, or 0.08} --point_num 600`

to at least

`python -m apps.gen_targets --dataroot {path_of_dataset} --sigma {0.003, 0.02, AND 0.08} --point_num 600`

to avoid confusion.

Maybe state that it needs to be run 3 times then.

**Comment by zhaofang0627** [comment]
Hi, thank you for your suggestion! I have updated the README to avoid confusion.

**Comment by kampelmuehler** [comment]
Thanks!
