### ISSUE TITLE
Input mesh scaling

### ISSUE THREAD

**Issue by kampelmuehler** [zhaofang0627/AnchorUDF#11]
Am I geussing correctly that you are uniformly scaling and translating ground truth meshes such that they fit within a box of [-0.5, 0.5]? Is it the same as here: https://github.com/jchibane/ndf/blob/master/dataprocessing/convert_to_scaled_off.py?

How do you take care of scaling back up (and potentially translating) at test time?

**Comment by zhaofang0627** [comment]
Hi, 

Yes,  the ground truth meshes are normalized to [-0.5, 0.5] which is the same as "convert_to_scaled_off.py" from ndf. 

For testing, you can refer to [compute_errors.py](https://github.com/zhaofang0627/AnchorUDF/blob/main/apps/compute_errors.py).
