### ISSUE TITLE
Missing data from the linked download page

### ISSUE THREAD

**Issue by fyviezhao** [zhaofang0627/AnchorUDF#12]
Hi, it seems that the [data downloading page](https://drive.google.com/drive/folders/1gXDlPGYYVad8IkFo_gxd-NOcFEgomwT0) lacks RENDER_512 and MASK_512 which lead to the `FileNotFoundError: [Errno 2] No such file or directory: '/data/Datasets/AnchorUDF/new_data_222/MASK/290-1/0_0_00.png'` when executing `apps.eval`. The `apps.eval_hd`  works fine however, as the RENDER_1024 and MASK_1024 are provided on the download page.

Is it OK to directly resize the 1024\*1024 rendered images and masks to 512\*512 and set them as the prepared data?

**Comment by zhaofang0627** [comment]
Hi, RENDER_512 and MASK_512 are not uploaded due to the storage space limitation. It is fine to resize 1024x1024 rendered images and masks to 512x512 as the prepared data.

**Comment by fyviezhao** [comment]
Very well, thanks and closed.
