### ISSUE TITLE
data_processing.

### ISSUE THREAD

**Issue by zhang-0515** [zhaofang0627/AnchorUDF#2]
import data_processing.implicit_waterproofing as iw

I cant't get data_processing.implicit_waterproofing 。Is it convenient to provide?

**Comment by zhaofang0627** [comment]
Hi,

I reorganize the code and the missing function is added to https://github.com/zhaofang0627/AnchorUDF/blob/3cf46d0d524503599d1dbfd48452f9e5019ad966/lib/mesh_util.py#L108

Best, 
Fang Zhao

**Comment by zhang-0515** [comment]
I’m sorry to bother you again. I want to ask if pytorch1.6 is used in both the testing phase and the training phase. The error is displayed here (_pickle.UnpicklingError: A load persistent id instruction was encountered, but no persistent_load...). The query shows that it is a torch version problem。thank you！


。。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhaofang0627/AnchorUDF"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月28日(星期四) 上午9:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhaofang0627/AnchorUDF] data_processing. (Issue #2)





 
Hi,
 
I reorganize the code and the missing function is added to https://github.com/zhaofang0627/AnchorUDF/blob/3cf46d0d524503599d1dbfd48452f9e5019ad966/lib/mesh_util.py#L108
 
Best,
 Fang Zhao
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhang-0515** [comment]
I’m sorry to bother you again. I want to ask if pytorch1.6 is used in both the testing phase and the training phase. The error is displayed here (_pickle.UnpicklingError: A load persistent id instruction was encountered, but no persistent_load...). The query shows that it is a torch version problem。

**Comment by zhang-0515** [comment]
I’m sorry to bother you again. I want to ask if pytorch1.6 is used in both the testing phase and the training phase. The error is displayed here (_pickle.UnpicklingError: A load persistent id instruction was encountered, but no persistent_load...). The query shows that it is a torch version problem。thank you！

**Comment by zhaofang0627** [comment]
Yes, both testing and training use pytorch1.6.

**Comment by zhang-0515** [comment]
非常抱歉，打扰您，我这边确实使用pytorch1.6进行了尝试，但是一直显示错误，您是否方便查看一下您的data.pkl文件是否正确

**Comment by zhaofang0627** [comment]
你好，data.pkl是指trained model文件吗？

**Comment by zhang-0515** [comment]
是的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhaofang0627/AnchorUDF"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月30日(星期六) 凌晨0:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhaofang0627/AnchorUDF] data_processing. (Issue #2)





 
你好，data.pkl是指trained model文件吗？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhang-0515** [comment]
在运行的demo时，--load_netG_checkpoint_path后面填写的那个地址中的内容是否为trained model中的data.pkl的地址啊
您可以帮我看看我的指令是否书写正确吗？
感谢您






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhaofang0627/AnchorUDF"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月30日(星期六) 凌晨0:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhaofang0627/AnchorUDF] data_processing. (Issue #2)





 
你好，data.pkl是指trained model文件吗？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhang-0515** [comment]
经过我的查询，可能是您再上传时pkl出现了错误，当我在尝试同一个虚拟环境下创建了一个新的py文件下读取data.pkl时，也是显示同样的错误，
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "张瑀卿"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月30日(星期六) 上午10:07
***@***.***&gt;;

主题:&nbsp;回复： [zhaofang0627/AnchorUDF] data_processing. (Issue #2)



在运行的demo时，--load_netG_checkpoint_path后面填写的那个地址中的内容是否为trained model中的data.pkl的地址啊
您可以帮我看看我的指令是否书写正确吗？
感谢您






------------------ 原始邮件 ------------------
发件人:                                                                                                                        "zhaofang0627/AnchorUDF"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月30日(星期六) 凌晨0:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhaofang0627/AnchorUDF] data_processing. (Issue #2)





 
你好，data.pkl是指trained model文件吗？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhaofang0627** [comment]
我这边重新下载模型文件然后读取，并没有发现问题，如下图：
<img width="867" alt="test_model_load" src="https://user-images.githubusercontent.com/11569189/139583385-484d2cb1-e062-4497-9a68-9cddc4c53e5d.png">
有没有可能是你的python版本的问题，我这里用的是python3.7

**Comment by zhang-0515** [comment]
我按照您这个输入后，显示找不到这个文件，请问您的netG_EPOCH_59里面是我这个样子的吗
![QQ截图20211101090945](https://user-images.githubusercontent.com/72601089/139608422-e640b24e-981e-400c-aed6-8911fefeea1c.jpg)
？

**Comment by zhaofang0627** [comment]
下载模型文件后不用解压缩，直接用pytorch载入。

**Comment by zhang-0515** [comment]
这样直接导入
![QQ截图20211101094952](https://user-images.githubusercontent.com/72601089/139610632-87d48a79-2c0c-4f5d-b81d-b02afaaa4a49.jpg)
？

**Comment by zhang-0515** [comment]
老师，这是按照计辅要求修改后的中英文摘要，麻烦老师帮我看一下，最近再把小论文修改一下，15号发给老师，谢谢老师
