### ISSUE TITLE
Dataset preparation

### ISSUE THREAD

**Issue by kampelmuehler** [zhaofang0627/AnchorUDF#5]
in `README.md` you state that data preparation follows the original `PIFu` data preparation steps. This does not generate any anchor points though. In the paper you describe that you use k-means clustering on randomly sampled points on the surface and use the cluster centers as anchor points. Is that correct? Can you please provide the code you used to calculate the keypoints/anchorpoints?

**Comment by zhaofang0627** [comment]
Actually, the keypoints/anchorpoints can be easily obtained by the following code:
```
import numpy as np
import trimesh
from sklearn.cluster import KMeans

sample_num = 100000 
point_num = 600

mesh = trimesh.load(input_mesh_path)
surface_points, _ = trimesh.sample.sample_surface(mesh, sample_num)
kmeans = KMeans(n_clusters=point_num, random_state=0).fit(surface_points)
key_points = kmeans.cluster_centers_

trimesh.Trimesh(vertices=key_points, faces=[]).export(out_file_off)
np.savez(out_file_path, kp=key_points)
```

**Comment by kampelmuehler** [comment]
Thanks you very much for sharing!
