### ISSUE TITLE
opt.ndf_pc does not exist in options

### ISSUE THREAD

**Issue by kampelmuehler** [zhaofang0627/AnchorUDF#6]
Thus I get the same error message for `eval.py` and `eval_hd.py`:

![grafik](https://user-images.githubusercontent.com/9306799/140271876-14529d8f-7f2f-46d7-b14d-bd05a3953ac7.png)

Is it meant to be `if "ndf_pc" in opt and opt.ndf_pc is True` ?

**Comment by zhaofang0627** [comment]
Sorry, "ndf_pc" is a obsolete flag, it is now fixed
